<?php

# Some labels
$home_title 		= "Domů";
$cart_title 		= "Košík";
$checkout_title 	= "K pokladně";
$login_title 		= "Login";
$logout_title 		= "Logout";
$browse_title		= "Procházet";
$search_title 		= "Hledat";
$account_title 		= "Nastavení<BR>účtu";
$navigation_title	= "Navigace";
$department_title	= "Kategorie";

$module_topmenu            = "$modulename/html/topmenu.ihtml";
$module_leftmenu            = "$modulename/html/leftmenu.ihtml";

$browse_lbl             = "Procházet";
$search_lbl             = "Hledat";
$flypage_lbl            = "Detaily";

$product_name_title     = "Jméno";
$product_category_title = "Kategorie";
$product_thumb_title 	= "Malý obrázek";
$product_price_title 	= "Cena";
$product_desc_title     = "Popis produktu";
$order_status =array();
$order_status["P"]["label"]= "Pending";
$order_status["C"]["label"]= "Potvrzeno";
$order_status["X"]["label"]= "Zrušeno";

$cart_name              = "Jméno";
$cart_sku               = "SKU";
$cart_price             = "Cena";
$cart_quantity          = "Kvantita";
$cart_subtotal          = "Mezisoučet";

# Some messages
$empty_cart             = "Váš košík je prázdný.";
$price_label            = "Cena: Kč ";
$order_button_label     = "Koupit";

?>
