<?php

# Some labels
$home_title 		= "Domů";
$cart_title 		= "Košík";
$checkout_title 	= "Objednávka";
$login_title 		= "Login";
$logout_title 		= "Logout";
$browse_title		= "Procházet";
$search_title 		= "Heldat";
$account_title 		= "Nastavení<BR>účtu";
$navigation_title	= "Navigace";
$department_title	= "Kategorie";

$module_topmenu            = "$modulename/html/topmenu.ihtml";
$module_leftmenu            = "$modulename/html/leftmenu.ihtml";

$browse_lbl             = "Procházet";
$search_lbl             = "Hledat";
$flypage_lbl            = "Detaily produktu";

$product_name_title     = "Jméno produktu";
$product_category_title = "Kategorie";
$product_desc_title     = "Popis";
$order_status =array();
$order_status["P"]["label"]= "Probíhá";
$order_status["C"]["label"]= "Potvrzeno";
$order_status["X"]["label"]= "Zrušeno";

$cart_name              = "Jméno";
$cart_sku               = "SKU";
$cart_price             = "Cena";
$cart_quantity          = "Množství";
$cart_subtotal          = "Subtotal";

# Some messages
$empty_cart             = "Váš košík je prázdný.";
$price_label            = "Cena: $";
$order_button_label     = "Objednávka";

?>
